(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Code:: *)
Int[f_'[x_],x_Symbol] :=
  f[x] /;
FreeQ[f,x]


(* ::Code:: *)
Int[Derivative[n_][f_][x_],x_Symbol] :=
  Derivative[n-1][f][x] /;
FreeQ[{f,n},x]


(* ::Code:: *)
Int[u_*g_'[x_],x_Symbol] :=
  Subst[Int[SimplifyIntegrand[SubstFor[g[x],u,x],x],x],x,g[x]] /;
FreeQ[g,x] && FunctionOfQ[g[x],u,x]


(* ::Code:: *)
Int[u_*Derivative[n_][g_][x_],x_Symbol] :=
  Subst[Int[SimplifyIntegrand[SubstFor[Derivative[n-1][g][x],u,x],x],x],x,Derivative[n-1][g][x]] /;
FreeQ[{g,n},x] && FunctionOfQ[Derivative[n-1][g][x],u,x]


(* ::Code:: *)
Int[f_'[x_]*g_[x_] + f_[x_]*g_'[x_],x_Symbol] :=
  f[x]*g[x] /;
FreeQ[{f,g},x]


(* ::Code:: *)
Int[(f_'[x_]*g_[x_] - f_[x_]*g_'[x_])/g_[x_]^2,x_Symbol] :=
  f[x]/g[x] /;
FreeQ[{f,g},x]


(* ::Code:: *)
Int[(f_'[x_]*g_[x_] - f_[x_]*g_'[x_])/(f_[x_]*g_[x_]),x_Symbol] :=
  Log[f[x]/g[x]] /;
FreeQ[{f,g},x]


(* ::Code:: *)
Int[(f_'[x_]*g_[x_] - f_[x_]*g_'[x_])/(f_[x_]^2 + g_[x_]^2),x_Symbol] :=
  ArcTan[f[x]/g[x]] /;
FreeQ[{f,g},x]


(* ::Code:: *)
Int[(f_'[x_]*g_[x_] - f_[x_]*g_'[x_])/(f_[x_]^2 - g_[x_]^2),x_Symbol] :=
  -ArcTanh[f[x]/g[x]] /;
FreeQ[{f,g},x]



